"""The Conductor's question banks, loaded from the compiled contract.

pmos/question_banks.json is generated by tools/question_banks.py from the six
Markdown banks in skills/conductor/questions/ and ships inside this package.
shipped_banks() turns it into QuestionBank objects in loop order, DISCOVER to
OPERATE. LEGACY_ONBOARDING is the one-question bank the CLI ran before the
contract existed: a product that started on it keeps it, so it still resumes.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

from .conductor import EvidenceClass, Question, QuestionBank
from .store import ValidationError


CONTRACT_PATH = Path(__file__).resolve().parent / "question_banks.json"
# Gate approvers stay the local attestation until approvals bind to roles.
LOCAL_APPROVERS = ("local-reviewer",)
LEGACY_ONBOARDING = (
    QuestionBank("onboarding", "v1", (
        Question("first-outcome", "What outcome should the first product user achieve?",
                 EvidenceClass.OBSERVED_BEHAVIOR),
    ), gate_approvers=LOCAL_APPROVERS),
)


def load_contract(path: str | Path = CONTRACT_PATH) -> dict[str, Any]:
    """The compiled contract as a dict, or a ValidationError when it cannot be used."""
    try:
        raw = Path(path).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise ValidationError("question bank contract is missing or unreadable: %s" % exc) from exc
    try:
        contract = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError("question bank contract is not valid JSON: %s" % exc) from exc
    if not isinstance(contract, dict) or contract.get("schema") != 1:
        raise ValidationError("question bank contract schema must be 1")
    banks = contract.get("banks")
    if not isinstance(banks, list) or not banks:
        raise ValidationError("question bank contract has no banks")
    return contract


def banks_from_contract(contract: Mapping[str, Any]) -> tuple[QuestionBank, ...]:
    """One QuestionBank per bank, in the contract's order.

    A malformed bank or question is a ValidationError, never a KeyError: a
    contract can come from outside the package, such as a product's pinned copy.
    """
    try:
        return tuple(
            QuestionBank(bank["id"], bank["version"],
                         tuple(Question(question["id"], question["ask"],
                                        EvidenceClass(question["evidence_class"]))
                               for question in bank["questions"]),
                         gate_approvers=LOCAL_APPROVERS)
            for bank in contract["banks"])
    except ValidationError:
        raise
    except (KeyError, TypeError, ValueError) as exc:
        raise ValidationError("question bank contract is malformed: %r" % (exc,)) from exc


def shipped_banks() -> tuple[QuestionBank, ...]:
    """The banks compiled into this package, DISCOVER to OPERATE."""
    return banks_from_contract(load_contract())
