#!/usr/bin/env python3
"""Generator for the "Example availability" paragraph in every domain knowledge card.

    python3 tools/example_availability.py            # rewrite it in every knowledge/domains/*.md
    python3 tools/example_availability.py --check    # exit 1 when any committed copy is stale

Standard library only, like every other script in this tree.

A domain card used to say in its own prose whether the templates it bends had been
filled anywhere in this repository. Seven cards were wrong: they denied examples the
tree already carried, and nothing noticed, because a sentence is not checked by
anything. This paragraph is a reading of declarations already in the tree, never a
second copy of them:

- examples/*.md declare which template they fill, in the "Fills [templates/...]"
  sentence in their opening lines, the same declaration tools/template_rubric.py
  --backpointers reads from the template's side;
- an example declares it was written for a domain by being named
  domain-<card-stem>-<template-stem>.md;
- a card declares which templates it bends in its "**Templates this bends:**" line.

Global existence and domain applicability are kept apart on purpose: "no example
covers this domain" can be true in a card whose "no example exists" is false.

--check also fails on a hand-written repository-wide absence claim left anywhere in a
card outside the generated block, because such a sentence is exactly what went stale
and nothing regenerates it. The same scan reads the two files beside the cards,
knowledge/domains/INDEX.md and knowledge/domains/README.md, which carry no generated
paragraph of their own: a claim moved one file out of a card is the same claim. A claim scoped to one domain is allowed and unaffected,
but the scoping phrase has to attach to the claim: only a connective from SCOPE_RE's
closed list may stand between them, and the phrase has to end the sentence. A claim
followed by any other clause is still a repository-wide claim, however that clause
ends. Markdown emphasis or a link around the template stem is a disguise rather than
a different sentence, so the claim is matched through both.

A card must carry exactly one generated block, opener first. A card carrying none,
and with no anchor to put one below, is a failure here rather than a card quietly
outside this gate; a card carrying a second block is refused because only the first
is ever regenerated; and a card whose closer precedes its opener is named here rather
than left to raise out of render(). A link whose text is a template directory,
"templates/ai/", declares every template in that directory, which is the pack the
card says it bends.

What this file does not claim: ABSENCE_RE is a finite list of the phrasings that went
wrong, not a reading of English, so a sentence that makes the same claim in words
nobody has used here yet will pass. The gate is a ratchet on known shapes.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- generated: example-availability -->"
END = "<!-- end generated: example-availability -->"
ANCHOR = "**Filled in this repo:**"
TAIL = "This paragraph is generated by `python3 tools/example_availability.py`."
TEMPLATE_RE = re.compile(r"templates/[a-z0-9-]+/[a-z0-9-]+\.md")
# A card declares a whole template pack by linking the directory itself: the link
# TEXT is "templates/<dir>/". One card (ai-products) does this, and reading only the
# file in that link's URL made the card claim it bends 2 templates when it declares
# a pack of eleven plus one more.
DIR_LINK_RE = re.compile(r"\[templates/([a-z0-9-]+)/\]\([^)]*\)")
# How many opening lines of an examples/ file declare which template it fills.
# The same window tools/template_rubric.py reads from the other side, so the two
# gates cannot disagree about what counts as a declared example.
NAMES_BACK_WITHIN = 5

# A template stem as a card writes one: bare, wrapped in markdown emphasis, or
# written as a link. Review found that a single backtick round the stem walked a
# claim past the bare \w+ this used to be, which is a disguise rather than a
# different statement.
STEM = r"(?:`[^`\n]+`|\*\*[^*\n]+\*\*|\*[^*\n]+\*|_[^_\n]+_|\[[^\]\n]+\]\([^)\n]*\)|\w+(?:-\w+)*)"
# Every way of saying "in this repository", including the generator's own wording,
# so a sentence cannot escape by borrowing the phrasing of the paragraph it sits by.
WHERE = r"(?:anywhere )?in (?:this|the) repository"
# A claim, in a card's own prose, that some kind of filled example does not exist
# anywhere in this repository. Each alternative is one of the shapes the seven stale
# cards actually used; the stem is optional because "No filled example exists in this
# repository" makes the same claim with no stem at all. A claim scoped to one domain
# is a different statement and is dropped in handwritten_absence() by SCOPE_RE.
ABSENCE_RE = re.compile(
    (r"no filled(?: %(stem)s)? example(?: of %(stem)s)? exists %(where)s"
     r"|no filled example %(where)s covers"
     r"|has no filled example %(where)s"
     r"|a filled %(stem)s example[^.\n]*?is not yet %(where)s"
     r"|not yet filled as standalone artifacts %(where)s"
     r"|has a filled example of its own yet either") % {"stem": STEM, "where": WHERE},
    re.IGNORECASE,
)
# What may stand between a claim and the phrase that narrows it to one domain: a
# closed list of connectives and nothing else. Review broke the earlier tail test
# four ways -- ", and none is planned for this domain.", "; that gap is the one that
# hurts for this domain.", " - a gap that matters for this domain.", and the same
# without the comma -- each a false repository-wide claim whose sentence merely ENDED
# with the scoping words. Ending a sentence is not governing the claim in it, so the
# phrase now has to attach to the claim itself.
SCOPE_RE = re.compile(r"\s*(?:(?:yet|still|so far|to date|as yet)\s+)*for this domain\s*$",
                      re.IGNORECASE)


def declared_examples(root: Path) -> dict:
    """Map each template path to the example files that declare they fill it."""
    out: dict = {}
    for f in (root / "examples").glob("*.md"):
        if f.name == "README.md":
            continue
        try:
            head = "\n".join(f.read_text(encoding="utf-8").splitlines()[:NAMES_BACK_WITHIN])
        except (UnicodeDecodeError, OSError):
            continue
        for m in set(TEMPLATE_RE.findall(head)):
            out.setdefault(m, []).append(f.name)
    return {k: sorted(set(v)) for k, v in out.items()}


def bent_templates(text: str, root: Path) -> list:
    """The template paths a domain card declares it bends, in the order written.

    A link whose text is a template directory ("templates/ai/") declares every
    template in that directory, which is what such a card says in its own words;
    a link to one file declares that file. A directory that does not exist
    declares nothing, and the file named in its URL is read as any other path.
    """
    for line in text.splitlines():
        if not line.startswith("**Templates this bends:**"):
            continue
        events = [(m.start(), "dir", m.group(1)) for m in DIR_LINK_RE.finditer(line)]
        events += [(m.start(), "path", m.group()) for m in TEMPLATE_RE.finditer(line)]
        seen, added = [], set()

        def add(path: str) -> None:
            if path not in added:
                seen.append(path)
                added.add(path)

        # Sorted by position, so a directory link is expanded before the path in
        # its own URL is reached and that path is already accounted for.
        for _, kind, value in sorted(events, key=lambda e: e[0]):
            if kind == "path":
                add(value)
                continue
            folder = root / "templates" / value
            if folder.is_dir():
                for f in sorted(folder.glob("*.md")):
                    if f.name != "README.md":
                        add("templates/%s/%s" % (value, f.name))
        return seen
    return []


def domain_examples(card_stem: str, names) -> list:
    """The example file names that declare they were written for this domain card."""
    prefix = "domain-%s-" % card_stem
    return sorted(n for n in names if n.startswith(prefix) and n.endswith(".md"))


def cards(root: Path) -> list:
    """Every domain card, sorted by path."""
    return sorted(f for f in (root / "knowledge" / "domains").glob("*.md")
                  if f.stem not in ("INDEX", "README"))


def sidecars(root: Path) -> list:
    """The two files in knowledge/domains/ that are not cards: its INDEX and its
    README. No paragraph is generated into them, because neither bends a
    template; they are read for hand-written absence claims and for nothing
    else, because a claim moved out of a card into the file next to it is the
    same claim about the same 47 cards' subject matter. Neither carries one
    today; this keeps the door shut rather than reporting that it is.
    """
    return sorted(f for f in (root / "knowledge" / "domains").glob("*.md")
                  if f.stem in ("INDEX", "README"))


def tlink(path: str) -> str:
    return "[%s](../../%s)" % (Path(path).stem, path)


def elink(name: str) -> str:
    return "[%s](../../examples/%s)" % (name, name)


def paragraph(card_stem: str, bent: list, rel: dict) -> str:
    """One generated paragraph of prose stating example availability."""
    head = "**Example availability (generated).** "
    if not bent:
        return head + ("This card declares no templates that it bends, so there is "
                       "nothing to report here. ") + TAIL
    filled = [t for t in bent if rel.get(t)]
    n, m = len(bent), len(filled)
    n_noun = "template" if n == 1 else "templates"
    out = head
    if not filled:
        out += ("None of the %d %s this card bends has a filled example anywhere in "
                "this repository. " % (n, n_noun)) if n != 1 else (
            "The one template this card bends has no filled example anywhere in this "
            "repository. ")
    else:
        listed = ", ".join("%s (%d)" % (tlink(t), len(rel[t])) for t in filled)
        out += "Of the %d %s this card bends, %d %s a filled example somewhere in this repository: %s. " % (
            n, n_noun, m, "has" if m == 1 else "have", listed)
    dom, dom_templates = set(), set()
    for t in filled:
        got = domain_examples(card_stem, rel[t])
        if got:
            dom.update(got)
            dom_templates.add(t)
    dom = sorted(dom)
    if dom:
        out += "Written for this domain: %s. " % ", ".join(elink(x) for x in dom)
    elif filled:
        out += ("No filled example in this repository was written for this domain; the "
                "examples above fill the same templates for other products. ")
    gone = [t for t in bent if not rel.get(t)]
    if gone and filled:
        out += "No filled example of %s exists anywhere in this repository. " % ", ".join(
            tlink(t) for t in gone)
    partial = [t for t in filled if t not in dom_templates]
    if partial and dom:
        out += "Filled examples of %s exist, but none was written for this domain. " % ", ".join(
            tlink(t) for t in partial)
    out += TAIL
    while "  " in out:
        out = out.replace("  ", " ")
    return out


def render(text: str, block: str) -> str:
    """The card text with the generated block in place, and nothing else changed.

    Idempotent, and it normalises its own spacing: the block always sits one blank
    line below the "Filled in this repo" paragraph and one blank line above whatever
    followed it, whether it is being inserted for the first time or replaced.

    It replaces the FIRST block only, and it returns the text untouched when there is
    neither a block nor an anchor. Both of those are how a card would slip out of this
    gate rather than fail it, so unplaceable() refuses such a card before we get here;
    this function is never the thing that decides a card is fine.
    """
    if BEGIN in text:
        start = text.index(BEGIN)
        finish = text.index(END, start) + len(END)
        head, tail = text[:start], text[finish:]
    else:
        head = None
        pos = 0
        for line in text.splitlines(keepends=True):
            pos += len(line)
            if line.startswith(ANCHOR):
                head, tail = text[:pos], text[pos:]
                break
        if head is None:
            return text
    return head.rstrip("\n") + "\n\n" + block + "\n\n" + tail.lstrip("\n")


def handwritten_absence(text: str, begin: str = BEGIN, end: str = END) -> list:
    """Repository-wide absence claims left in a card's own prose, outside the block.

    Only the FIRST marker pair is dropped, because render() regenerates only the
    first pair: prose parked inside a second, hand-added pair is regenerated by
    nothing and is read here like any other prose. A card carrying a second pair
    is refused outright in main(); this is the second lock on the same door.

    Line breaks are collapsed before the scan, because a claim that wraps across two
    lines is the same sentence to a reader and was not to the regex.

    The scoping test is an attachment test. Everything between the claim and "for
    this domain" has to be a connective from SCOPE_RE's closed list, and the phrase
    has to reach the end of the sentence: that is the whole of what this code
    checks, and no more is claimed for it. A sentence that makes a repository-wide
    claim and then opens any other clause is still a repository-wide claim, whether
    that clause is introduced by a comma, a semicolon, a dash or a bare "and", and
    whether or not it happens to end in the scoping words.
    """
    start = text.find(begin)
    if start != -1:
        finish = text.find(end, start)
        if finish != -1:
            text = text[:start] + text[finish + len(end):]
    # Read the prose the way a reader does, so a claim that happens to wrap across
    # two lines is the same claim as one written on a single line.
    text = " ".join(text.split())
    found = []
    for match in ABSENCE_RE.finditer(text):
        rest = text[match.end():]
        cut = rest.find(".")
        segment = rest[:cut if cut != -1 else len(rest)]
        if SCOPE_RE.fullmatch(segment):
            continue
        found.append(match.group())
    return sorted(set(found))


def unplaceable(text: str) -> str:
    """Why this card cannot carry exactly one generated block, or "" when it can.

    render() leaves a card untouched when there is nowhere to put the block, and
    it rewrites only the first of several blocks. Either state would take the
    card out of this gate silently, so both are named failures instead: a card
    is in the gate or the gate fails.
    """
    begins, ends = text.count(BEGIN), text.count(END)
    if begins > 1 or ends > 1:
        return ("carries %d generated block openers and %d closers; exactly one of "
                "each is allowed, because only the first is regenerated" % (begins, ends))
    if begins != ends:
        return "carries %d generated block openers and %d closers" % (begins, ends)
    if begins == 0 and ANCHOR not in text:
        return ("has neither a generated block nor a %r line to put one below, so "
                "nothing about it is generated" % ANCHOR)
    if begins == 1 and text.index(END) < text.index(BEGIN):
        return ("carries its generated block closer before its opener, so there is no "
                "block between them to read or regenerate")
    return ""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when any card's generated paragraph is stale or "
                             "missing, or when a card's prose still claims a "
                             "repository-wide absence")
    args = parser.parse_args(argv)

    rel = declared_examples(ROOT)
    stale, claims, broken, rewrote, total = [], [], [], 0, 0
    for path in cards(ROOT):
        text = path.read_text(encoding="utf-8")
        rel_path = path.relative_to(ROOT).as_posix()
        total += 1
        reason = unplaceable(text)
        if reason:
            broken.append((rel_path, reason))
            continue
        block = BEGIN + "\n" + paragraph(path.stem, bent_templates(text, ROOT), rel) + "\n" + END
        new = render(text, block)
        if new != text:
            stale.append(rel_path)
            if not args.check:
                path.write_text(new, encoding="utf-8")
                rewrote += 1
        for claim in handwritten_absence(new if not args.check else text):
            claims.append((rel_path, claim))

    for path in sidecars(ROOT):
        for claim in handwritten_absence(path.read_text(encoding="utf-8")):
            claims.append((path.relative_to(ROOT).as_posix(), claim))

    for p, reason in broken:
        print("%s: %s: %s" % ("no generated block" if args.check else
                              "cannot write", p, reason))
    if args.check:
        for p in stale:
            print("stale: %s" % p)
        for p, claim in claims:
            print("hand-written absence claim: %s: %r" % (p, claim))
        if stale or claims or broken:
            print("%d stale, %d hand-written absence claim(s), %d card(s) outside the "
                  "generated block; run python3 tools/example_availability.py, and "
                  "either delete a hand-written claim or make it true of one domain "
                  "by ending its sentence with 'for this domain' straight after the "
                  "claim (only 'yet', 'still', 'so far', 'to date' or 'as yet' may "
                  "stand between): a claim followed by any other clause is still a "
                  "claim about the whole repository"
                  % (len(stale), len(claims), len(broken)))
            return 1
        print("%d cards fresh" % total)
        return 0

    for p, claim in claims:
        print("hand-written absence claim left in %s: %r" % (p, claim))
    print("rewrote %d of %d cards" % (rewrote, total))
    return 1 if claims or broken else 0


if __name__ == "__main__":
    sys.exit(main())
