#!/usr/bin/env python3
"""Generator for the "What checks this" text in every prose skill and every template.

    python3 tools/what_checks.py            # rewrite it in every skills/*/SKILL.md and templates/**/*.md
    python3 tools/what_checks.py --check    # exit 1 when any committed copy is stale

Standard library only, like every other script in this tree.

In a skill it is the last section and says which rules a tool enforces and which
rest with a person. In a template it is one paragraph under the Stage/Knowledge/
Skill header and tells whoever fills the copy what binds it once it is stamped.
It is a reading of declarations already in the tree, never a second copy of them:

- a skill's SKILL.graph.yml, or a template's frontmatter, for the gate it is declared against
  (tools/workspace.py stamps a filled copy's artifact block from that same frontmatter);
- skills/conductor/questions/*.md, for which question bank records which gate;
- the sign-off tables in os/STAGE-GATES.md, for who signs each gate.

The runtime behaviour the section describes is pmos/conductor.py's gate proof,
stated at the strength os/STAGE-GATES.md gives it: approver ids are typed, not
authenticated. When a declaration changes, --check fails until this is re-run.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARK = "## What checks this"

RUNTIME_RULES = (
    "which refuses the proof unless every question in that bank has been accepted and the bank is the current one, "
    "requires the proof to name its `source`, `source_sha256`, `actor_id`, `requester_id`, `decision` and "
    "`approved_at`, and rejects self-approval and any approver the bank does not pin. Approver ids are typed, not "
    "authenticated, so a recorded approval is a local attestation, not proof of who signed. If the proof's source "
    "changes after approval the gate goes stale and nothing later completes until it is proved again. "
    "[The journey run](../../examples/journey-run.md) shows all six gates and a stale gate being proved again."
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def banks() -> dict[int, str]:
    """Gate number to bank id, read from each question bank's own frontmatter."""
    out = {}
    for f in sorted((ROOT / "skills/conductor/questions").glob("*.md")):
        if f.name == "README.md":
            continue
        m = re.search(r"^gate:\s*(\d)\s*$", read(f), re.M)
        if m:
            out[int(m.group(1))] = f.stem
    return out


def signoffs() -> dict[int, list[str]]:
    """Gate number to the roles in its sign-off table in os/STAGE-GATES.md."""
    text = read(ROOT / "os/STAGE-GATES.md")
    out = {}
    for m in re.finditer(r"^## Gate ([1-6]):.*?(?=^## Gate [1-6]:|\Z)", text, re.S | re.M):
        t = re.search(r"^\| Sign-off \| Name \| Date \|\n\|[-| ]+\|\n((?:\|.*\|\n?)+)", m.group(0), re.M)
        if t:
            out[int(m.group(1))] = [row.split("|")[1].strip() for row in t.group(1).strip().splitlines()]
    return out


def declared(skill_dir: Path) -> tuple[str, int | None]:
    y = read(skill_dir / "SKILL.graph.yml")
    stage = re.search(r"^stage:\s*(.+?)\s*$", y, re.M)
    gate = re.search(r"^gate:\s*(\d)\s*$", y, re.M)
    return (stage.group(1) if stage else ""), (int(gate.group(1)) if gate else None)


def role_list(roles: list[str]) -> str:
    # Lower-case a role's first letter unless it opens an acronym ("QA owner").
    r = ["the " + (x if x[1:2].isupper() else x[0].lower() + x[1:]) for x in roles]
    return r[0] if len(r) == 1 else ", ".join(r[:-1]) + " and " + r[-1]


def section(skill_dir: Path, bank_of: dict[int, str], signs: dict[int, list[str]]) -> str:
    name = skill_dir.name
    stage, gate = declared(skill_dir)
    every_stage = stage.upper() == "ALL STAGES" or gate not in bank_of
    lines = [
        MARK, "",
        "Some checks on this skill run automatically and some depend on a person. This section says which is which. "
        "It is generated by `python3 tools/what_checks.py` "
        "from the declarations it links to, and CI fails when it falls out of date.", "",
        "- **Checked by CI on every commit.** This file must carry the seven sections every prose skill carries: "
        "`python3 tools/skill_rubric.py --min 7` fails the `skill-rubric` gate in `python3 tools/ci_gate.py` when one is "
        "missing. That checks structure, not whether the advice is right.",
    ]
    if name == "conductor":
        lines.append("- **Checked by the runtime.** The six question banks this skill interviews through are executed by "
                     "the `pmos` command line, and each gate is recorded with `pmos gate --bank-id <bank>`, " + RUNTIME_RULES)
    elif every_stage:
        lines.append("- **Checked by the runtime.** This skill is declared for all stages in [SKILL.graph.yml](SKILL.graph.yml), "
                     "so it can come before any of the six gates. Each gate is recorded with `pmos gate --bank-id <bank>`, " + RUNTIME_RULES)
    else:
        lines.append(f"- **Checked by the runtime.** This skill is declared against Gate {gate} in "
                     f"[SKILL.graph.yml](SKILL.graph.yml). Gate {gate} is recorded with `pmos gate --bank-id {bank_of[gate]}`, "
                     + RUNTIME_RULES)
    who = ("The product owner signs all six gates; each gate's other sign-offs are listed in "
           "[os/STAGE-GATES.md](../../os/STAGE-GATES.md).") if (name == "conductor" or every_stage) else (
           f"Gate {gate} is signed by {role_list(signs[gate])}, per the sign-off tables in "
           "[os/STAGE-GATES.md](../../os/STAGE-GATES.md).")
    lines.append("- **Checked by a person.** The runtime checks who approved and that the evidence has not changed. It does "
                 "not check whether the reasoning in this skill's Workflow was followed well; that judgment belongs to the "
                 "people who sign the gate. " + who)
    return "\n".join(lines) + "\n"


def rendered(skill_md: Path, body: str) -> str:
    base = body[:body.index("\n" + MARK)] if ("\n" + MARK) in body else body
    bank_of, signs = banks(), signoffs()
    return base.rstrip("\n") + "\n\n" + section(skill_md.parent, bank_of, signs)


TEMPLATE_MARK = "**What checks this.**"


def template_paragraph(path: Path, gate: int, bank_of: dict[int, str], signs: dict[int, list[str]]) -> str:
    rel = Path(__import__("os").path.relpath(ROOT / "os/STAGE-GATES.md", path.parent)).as_posix()
    return (f"{TEMPLATE_MARK} A filled copy is bound to Gate {gate} once it carries the artifact block, which "
            f"`python3 tools/init_product.py <product> --stamp` writes from this template's own frontmatter. Approving "
            f"Gate {gate} with `pmos gate --bank-id {bank_of[gate]}` then records the copy's revision, and any later edit "
            f"makes that approval stale until the gate is proved again. Gate {gate} is signed by {role_list(signs[gate])}, "
            f"per [os/STAGE-GATES.md]({rel}). No tool checks whether what you write is right; the people who sign the "
            f"gate do. This paragraph is generated by `python3 tools/what_checks.py`.")


def template_rendered(path: Path, body: str, bank_of, signs) -> str | None:
    fm = re.match(r"\A---\n(.*?)\n---\n", body, re.S)
    g = re.search(r"^gate:\s*(\d)\s*$", fm.group(1), re.M) if fm else None
    if not g or int(g.group(1)) not in bank_of:
        return None
    # Drop any earlier copy of the paragraph, then place it after the whole
    # Stage/Knowledge/Skill header paragraph, so a second run changes nothing.
    body2 = "\n".join(l for l in body.split("\n") if not l.startswith(TEMPLATE_MARK))
    m = re.search(r"^(\*\*)?Skill:(\*\*)?", body2, re.M)
    if not m:
        return None
    cut = body2.find("\n\n", m.start())
    cut = len(body2) if cut < 0 else cut
    head, rest = body2[:cut].rstrip("\n"), body2[cut:].lstrip("\n")
    return head + "\n\n" + template_paragraph(path, int(g.group(1)), bank_of, signs) + "\n\n" + rest


def templates() -> list[Path]:
    return sorted(p for p in (ROOT / "templates").rglob("*.md") if p.name != "README.md")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when a committed section is stale")
    args = parser.parse_args(argv)
    stale = []
    for skill_md in sorted((ROOT / "skills").glob("*/SKILL.md")):
        if not (skill_md.parent / "SKILL.graph.yml").exists():
            continue
        body = read(skill_md)
        want = rendered(skill_md, body)
        if want != body:
            if args.check:
                stale.append(str(skill_md.relative_to(ROOT)))
            else:
                skill_md.write_text(want, encoding="utf-8")
                print(f"wrote {skill_md.relative_to(ROOT)}")
    bank_of, signs = banks(), signoffs()
    for tpl_path in templates():
        body = read(tpl_path)
        want = template_rendered(tpl_path, body, bank_of, signs)
        if want is None or want == body:
            continue
        if args.check:
            stale.append(str(tpl_path.relative_to(ROOT)))
        else:
            tpl_path.write_text(want, encoding="utf-8")
            print(f"wrote {tpl_path.relative_to(ROOT)}")
    if args.check:
        if stale:
            print("stale 'What checks this' text; run python3 tools/what_checks.py and commit:")
            for s in stale:
                print(f"  {s}")
            return 1
        print("every skill's and template's 'What checks this' text matches its declarations")
    return 0


if __name__ == "__main__":
    sys.exit(main())
